# Tarea 2 - Cifrado Moderno - Simetría
### Asignatura: Criptografía y Seguridad de la Información - TEL252-S2-2023
#### _Docente y Autor : Berioska Contreras Vargas - berioska.contreras@usm.cl_

### Construcción de bloques programáticos: 

* **Numpy:** es una biblioteca para programación en lenguaje Python que extiende el soporte para arreglos multi-dimensionales y matrices. Además, cuenta con una colección de funciones matemáticas de alto nivel.

<div style="text-align: center">Instalación: $ pip install numpy</div>
<div style="text-align: center"></div>

| Enlace | Descripción | 
| - | - |
| [Numpy](https://numpy.org/install/) | Instalando Numpy |

In [1]:
import numpy as np 
#np.__version__         # verificar versión
a = [0, 1, 2, 3, 4]
a_np = np.array(a)      # creando un arreglo
"""a_np                    # accediendo al arreglo completo
a_np[2]                 # accediendo a un valor específico
a_np[::2]"""               
print (a_np.tolist())     # convirtiendo el arreglo en lista
print (a_np + 10)
print (a_np * 5)

[0, 1, 2, 3, 4]
[10 11 12 13 14]
[ 0  5 10 15 20]


* **Aritmética Modular:** La aritmética modular nos ayuda a realizar un cómputo lineal y reversible en conjuntos finitos.

In [2]:
import numpy as np 
a = [0, 1, 2, 3, 4, 5, 6, 7]
x = [0, 1, 2, 3, 4, 5, 6, 7]
a_np = np.array(a)
x_np = np.array(x)
print ((a_np + x_np) % 8) 
print ((a_np * x_np) % 8)

[0 2 4 6 0 2 4 6]
[0 1 4 1 0 1 4 1]


* **XOR o Exclusive OR:** es una operación lógica que denota una desigualdad, es decir, el resultado es verdadero si los valores son distintos, de otra forma es falso. También, representa una adición módulo 2. En Python el operador `^` ("_caret_") es equivalente al operador XOR, mientras que el símbolo `&` representa al operador lógico AND. 

In [3]:
import numpy as np
a = np.array([[0,0],[1,1]])
x = np.array([[1,0],[0,1]])
print(a ^ x) # bitwise XOR
print(a & x) # bitwise AND

[[1 0]
 [1 0]]
[[0 0]
 [0 1]]


* **Máximo Común Divisor:** Identifica un valor que divide a ambos factores de entrada y que en criptografía permite permite identificar valores relativamente primos e inverso modular. 

In [2]:
import math
r0=56; r1=15
print (math.gcd(r0,r1))

1


* **Algoritmo de Euclides Extendido:** Permite una búsqueda eficiente de factores relativamente primos. También, es muy relevante en criptografía de llave pública.

In [13]:
def eea(r0,r1):
    if r0 == 0:
        return (r1, 0, 1)
    else:
        g, s, t = eea(r1 % r0, r0)
        return (g, t - (r1 // r0) * s, s)
r0, r1 = 20, 29
print(eea(r0,r1))

(1, -13, 9)


* **Función Phi de Euler o Totient de Euler:** Identifica cuántos números coprimos existen en un campo finito dado. La función Phi(n) es iterativa utilizando una factorización canónica de números primos.

| Enlace | Descripción | 
| - | - |
| [Sage](https://doc.sagemath.org/html/en/thematic_tutorials/numtheory_rsa.html) | Teoría de Números |

In [7]:
from math import gcd
def myeuler(m):
    phi = 0
    for a in range(1,m):
        if (gcd(a,m) == 1): 
            phi += 1
    return phi
Zm = 81
print("Phi(m): ",myeuler(Zm))

Phi(m):  54


* **Cifrado Simétrico:** transformación que actúa sobre una secuencia de bits en texto claro. El cifrado de llave secreta utiliza una misma llave pre-compartida. 

In [8]:
import numpy as np 
k = np.array([1, 2, 3, 4, 5])
m = np.array([2, 4, 6, 8, 10])
y = ((m ^ k) % 2)
print(y)

[1 0 1 0 1]


* RAND: función que genera números pseudoaleatorios

In [2]:
from numpy.random import rand
c = rand(3, 3)
print (c)

[[0.4361106  0.89813883 0.34025541]
 [0.49670942 0.98268482 0.29721768]
 [0.69343062 0.77190557 0.4726765 ]]


**Actividad 1 (50%)**: Analizar el siguiente código adaptado del cifrado de sustitución Affine. Proponga un código de búsqueda exhaustiva que demuestre la debilidad del algoritmo Affine. Explique su planteamiento.

In [1]:
import random, string, math
alpha = string.ascii_letters+string.digits+string.punctuation+' '
def main():
    m = "Mensaje secreto"
    k = getRandomk()
    c = encrypt(k, m)
    print(c)
    
def getkeys(k):
    k1 = k // len(alpha)
    k2 = k % len(alpha)
    return (k1,k2)
 
def encrypt(k, m):
    k1,k2 = getkeys(k)
    ciphertext = ''
    for symbol in m:
        if symbol in alpha:
            symbolIndex = alpha.find(symbol)
            ciphertext += alpha[(symbolIndex *k1 +k2) % len(alpha)]
        else:
            ciphertext += symbol
    return ciphertext

def getRandomk():
    while True:
        k1 = random.randint(2, len(alpha))
        k2 = random.randint(2, len(alpha))
        if math.gcd(k1, len(alpha)) == 1:
            return k1 * len(alpha) + k2

if __name__ == '__main__':
    main()

a:${th:0{:WC:5G


In [3]:
# Escriba aquí su código y markdown
#El codigo prueba todas las posibles convinaciones de k1 y k2,
#cada vez que encuentre una combinación imprime el mensaje

#me muestra todas las posibles llaves con su posible mensaje
#el usuario debe encontrar la que tenga sentido
import string

#alfabeto del cifrado
alpha = string.ascii_letters + string.digits + string.punctuation + ' '

def decrypt(k1, k2,  texto_cifrado):  #proceso de descifrado usando k1 Y k2
    plaintext = ''
    #Calcula el inverso multiplicativo de k1 (solo si es coprimo con la longitud de alpha)
    for symbol in texto_cifrado:
        if symbol in alpha:
            symbolIndex = alpha.find(symbol)
            #fórmula de descifrado
            inverse_k1 = mod_inverse(k1, len(alpha))
            decrypted_index = (inverse_k1 * (symbolIndex - k2)) % len(alpha)
            plaintext += alpha[decrypted_index]
        else:
            plaintext += symbol
    return plaintext

def mod_inverse(a, m):
    #inverso multiplicativo de a modulo m
    #se hace para encontrar la inversa de k1
    #estamos buscando un valor coprimo
    for x in range(1, m):
        if (a * x) % m == 1:
            return x
    return None
    #si no es coprimo se devuelve none


def brute_force_decrypt(texto_cifrado):#esta funciona intenta todas las combinaciones de k1 y k2
    #ya que k1 es coprimo se puede realizar un descifrado
    possible_decryptions = [(k1, k2, decrypt(k1, k2, texto_cifrado))
                            for k1 in range(2, len(alpha))
                            for k2 in range(2, len(alpha))
                            if mod_inverse(k1, len(alpha)) is not None]

    for k1, k2, plaintext in possible_decryptions:
        print(f'Intentando con k1={k1}, k2={k2}: {plaintext}')

texto_cifrado = "a:${th:0{:WC:5G"  #aqui ponemos el texto cifrado que nos entrega el affine anterior
brute_force_decrypt(texto_cifrado)

Intentando con k1=2, k2=2:  \<S4Y\zS\xn\.p
Intentando con k1=2, k2=3: ULF|icL+|L)8LB!
Intentando con k1=2, k2=4: ~[;R3X[yR[wm[-o
Intentando con k1=2, k2=5: TKE{hbK*{K(7KA9
Intentando con k1=2, k2=6: }@:Q2W@xQ@vl@,n
Intentando con k1=2, k2=7: SJD`gaJ)`J'6Jz8
Intentando con k1=2, k2=8: |?/P1V?wP?uk?+m
Intentando con k1=2, k2=9: RIC_f I(_I&5Iy7
Intentando con k1=2, k2=10: {>.O0U>vO>tj>*l
Intentando con k1=2, k2=11: QHB^e~H'^H%4Hx6
Intentando con k1=2, k2=12: `=-NZT=uN=si=)k
Intentando con k1=2, k2=13: PGA]d}G&]G$3Gw5
Intentando con k1=2, k2=14: _<,MYS<tM<rh<(j
Intentando con k1=2, k2=15: OFz\c|F%\F#2Fv4
Intentando con k1=2, k2=16: ^;+LXR;sL;qg;'i
Intentando con k1=2, k2=17: NEy[b{E$[E"1Eu3
Intentando con k1=2, k2=18: ]:*KWQ:rK:pf:&h
Intentando con k1=2, k2=19: MDx@a`D#@D!0Dt2
Intentando con k1=2, k2=20: \/)JVP/qJ/oe/%g
Intentando con k1=2, k2=21: LCw? _C"?C9ZCs1
Intentando con k1=2, k2=22: [.(IUO.pI.nd.$f
Intentando con k1=2, k2=23: KBv>~^B!>B8YBr0
Intentando con k1=2, k2=24: @-'HTN-oH-mc

* **One Time Pad:** De acuerdo a Claude Shannon, al menos tres son los principios que permiten otorgar un secreto perfecto. Uno de ellos es una llave impredecible.

In [3]:
import string
import secrets as prng
a = prng.randbelow(25) # función más robusta que rand
#print (a)
b = prng.choice(string.ascii_letters)
#print(b)
c = prng.choice(['apruebo','rechazo','nulo','blanco'])
print(c)

rechazo


* **Módulo Secrets:** Genera números aleatorios de manera segura para gestión de secretos. Es próximo a un generador criptográfico y más seguro que el módulo random.

In [14]:
# Ejemplo Selección aleatoria de los elementos de una cadena de caracteres.
import string, secrets as prng
ps = ''
for i in range(13):
    ps+=prng.choice(string.ascii_letters)
print (ps)

cwZVjKrPsQOSm


* **Módulo Secrets:** Generar una contraseña alfanumérica de N caracteres de longitud.

In [5]:
import string, secrets
alphabet = string.ascii_letters + string.digits
password = ''.join(secrets.choice(alphabet) for i in range(16))
print(password)

HFaNQhTTzuIm2nlR


* **Proyecto PyLFSR:** Proyecto que propone una función generadora de registros de desplazamiento de retroalimentación lineal, y perfectible. 

| Enlace | Descripción | 
| - | - |
| [PyLFSR](https://pypi.org/project/pylfsr/) | LFSR en Python |

In [4]:
# Ejemplo: Polinomio primitivo por omisión x^5 + x^2 + 1
import numpy as np
from pylfsr import LFSR
L = LFSR()
L.info()  
L.runFullCycle()

5 bit LFSR with feedback polynomial  x^5 + x^2 + 1
Expected Period (if polynomial is primitive) =  31
Current :
 State        :  [1 1 1 1 1]
 Count        :  0
 Output bit   :  -1
 feedback bit :  -1


array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0])

In [3]:
# Ejemplo: Polinomio primitivo propuesto x^4 + x + 1
import numpy as np
from pylfsr import LFSR
estado = [1,0,0,0]
polinomio = [3,1]
L = LFSR(fpoly=polinomio,initstate =estado, verbose=True)
L.info()
L.runKCycle(15)

3-bit LFSR with feedback polynomial  x^3 + x^1 + 1 with
Expected Period (if polynomial is primitive) =  7
Computing configuration is set to Fibonacci with output sequence taken from 3-th (-1) register
Current :
 State        :  [1 0 0 0]
 Count        :  0
 Output bit   :  -1
 feedback bit :  -1
S:  [1 0 0 0]
S:  [1 1 0 0]
S:  [1 1 1 0]
S:  [0 1 1 1]
S:  [1 0 1 1]
S:  [0 1 0 1]
S:  [0 0 1 0]
S:  [1 0 0 1]
S:  [1 1 0 0]
S:  [1 1 1 0]
S:  [0 1 1 1]
S:  [1 0 1 1]
S:  [0 1 0 1]
S:  [0 0 1 0]
S:  [1 0 0 1]


array([0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1])

In [52]:
# Ejemplo: Listar polinomios primitivos conocidos
L = LFSR()
fpolyDict = L.get_fpolyList(m=2)
print (fpolyDict)
fpolyDict = L.get_fpolyList()
print (fpolyDict)

[[2, 1]]
{2: [[2, 1]], 3: [[3, 1]], 4: [[4, 1]], 5: [[5, 2], [5, 4, 2, 1], [5, 4, 3, 2]], 6: [[6, 1], [6, 5, 2, 1], [6, 5, 3, 2]], 7: [[7, 1], [7, 3], [7, 3, 2, 1], [7, 4, 3, 2], [7, 5, 4, 3, 2, 1], [7, 6, 3, 1], [7, 6, 4, 2], [7, 6, 5, 2], [7, 6, 5, 4, 2, 1]], 8: [[8, 4, 3, 2], [8, 5, 3, 1], [8, 6, 4, 3, 2, 1], [8, 6, 5, 1], [8, 6, 5, 2], [8, 6, 5, 3], [8, 7, 6, 1], [8, 7, 6, 5, 2, 1]], 9: [[9, 4], [9, 5, 3, 2], [9, 6, 4, 3], [9, 6, 5, 3, 2, 1], [9, 6, 5, 4, 2, 1], [9, 7, 6, 4, 3, 1], [9, 8, 4, 1], [9, 8, 5, 4], [9, 8, 6, 5], [9, 8, 6, 5, 3, 1], [9, 8, 7, 2], [9, 8, 7, 3, 2, 1], [9, 8, 7, 6, 5, 1], [9, 8, 7, 6, 5, 3]], 10: [[10, 3], [10, 4, 3, 1], [10, 6, 5, 3, 2, 1], [10, 8, 3, 2], [10, 8, 4, 3], [10, 8, 5, 1], [10, 8, 5, 4], [10, 8, 7, 6, 5, 2], [10, 8, 7, 6, 5, 4, 3, 1], [10, 9, 4, 1], [10, 9, 6, 5, 4, 3, 2, 1], [10, 9, 8, 6, 3, 2], [10, 9, 8, 6, 5, 1], [10, 9, 8, 7, 6, 5, 4, 3]], 11: [[11, 2], [11, 5, 3, 1], [11, 5, 3, 2], [11, 6, 5, 1], [11, 7, 3, 2], [11, 8, 5, 2], [11, 8, 6, 5,

* **Múltiples Generadores:** El sistema global de comunicaciones móviles GSM utiliza encriptación de llamadas utilizando la familia de algoritmos A5. El algoritmo A5/1 es un cifrado simétrico por flujos A5/1. Inicialmente A5/1 fue un algoritmo secreto que con el tiempo demostró debilidades. Dentro de las propuestas de mejoramimento, se encuentran la modificación del polinomio del LFSR, y el uso aleatorio de múltiples registros LFSR. Tiempo después, la versión A5/2 demostró imperfecciones, quedando rápidamente obsoleta. En el año 2007, se define como nuevo estándar para las redes 3GPP al algoritmo A5/3 Kasumi, cifrado simétrico por bloques. 

| Enlace | Descripción | 
| - | - |
| [IEEE](https://doi.org/10.1109/ETNCC.2011.5958486) | Enhancement of A5/1 |
| [3GPP Security](https://portal.3gpp.org/desktopmodules/Specifications/SpecificationDetails.aspx?specificationId=2387) | Kasumi Specification |


In [27]:
# Múltiples generadores LFSR inicializados
R1 = LFSR(fpoly = [19,18,17,14])
R2 = LFSR(fpoly = [23,22,21,8])
R3 = LFSR(fpoly = [22,21])

# Bits de reloj
b1 = R1.state[8]
b2 = R1.state[10]
b3 = R1.state[10]

**Actividad 2 (50%)**: Construir un registro de desplazamiento de retroalimentación lineal eficiente para un campo finito binario, que cumpla con:
- Utilizar un polinomio primitivo de grado mayor a 30.
- Demuestre que la llave de flujo es consistente con el periodo máximo.
- No es posible invocar funciones LFSR preexistentes p.e. PyLFSR.

In [40]:
# Escriba aquí su código y markdown

# Se tomo la decision de ocupar el polinomio x^31+x^3+1 por la tabla de polinomios primitivos
# Ya que cumple con la 1era y 2do condicion impuesta por el enunciado
# Para la 3ra condicion se creo la funcion myOwnLFSR (inspirandonos por los codigos mostrados anteriormente en este jupyter)
import numpy as np

def myOwnLFSR(state,polinomio):
    i=0
    llave1er = np.empty(0,int) #La existencia de los dos arreglos de llaves es por si se quiere confirmar que efectivamente tiene un periodo igual a 2^n-1
    llave2do = np.array(0,int) #Si bien no es necesario para demostrar la 2da condicion, ya que el periodo puede desplazarse segun el estado inicial.
                  #Es una buena referencia, en el caso del polinomio escogido aumenta al DOBLE la duracion de la funcion para tenerlo en cuenta al momento de correr el programa
    print("No" + str(i) + "\t\t " + str(state))
    while i<2*(2**(polinomio[0])-1): #El for calcula dos periodos para demostrar que se cumple con el periodo maximo
        new_elem = state[0]
        for j in polinomio:
            new_elem = (new_elem + state[j])%2
        new_state = np.append([new_elem],state[:-1])
        if i<(2**(polinomio[0])-1):
            llave1er = np.append(llave1er,[state[-1]])
        else:
            llave2do = np.append(llave2do,[state[-1]])
        state = np.array(new_state)
        i=i+1
        #if i % 1000 == 0: #Estas dos lineas eran para verificar que se estuviera ejecutando el codigo sin llenar de mensajes la consola
        #    print(i)
        if i<5:     #primeras 5 itereaciones
            print("No" + str(i) + "\t\t " + str(state))
        if i==5:
            print("...")
        if i+5 >= 2*(2**(polinomio[0])-1) and i>5: #ultimas 5 iteraciones
            print("No" + str(i) + "\t\t " + str(state))

    print("Llave de flujo 1er Ciclo:\t " + str(llave1er[:20])+"..."+str(llave1er[-5:])) #para poder comparar las llaves obtenidas
    print(len(llave1er))
    print("Llave de flujo 2do Ciclo:\t " + str(llave2do[:20])+"..."+str(llave2do[-5:]))
    print(len(llave2do)) 

polinomio = [31,3] #polinomio escogido x^31+x^3+1, guiandonos por la tabla de polinomios primitivos
state = np.array([0,1,0,1,1,0,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,1,1,1,1,0,0,0,1,0,1,0])
polinomio = [3,1]
state = np.array([1,0,0,0])
myOwnLFSR(state,polinomio)


No0		 [1 0 0 0]
No1		 [1 1 0 0]
No2		 [0 1 1 0]
No3		 [1 0 1 1]
No4		 [0 1 0 1]
...
No9		 [0 1 1 0]
No10		 [1 0 1 1]
No11		 [0 1 0 1]
No12		 [0 0 1 0]
No13		 [0 0 0 1]
No14		 [1 0 0 0]
Llave de flujo 1er Ciclo:	 [0 0 0 1 1 0 1]...[0 1 1 0 1]
7
Llave de flujo 2do Ciclo:	 [0 0 0 0 1 1 0 1]...[0 1 1 0 1]
8


Adjunto imagen con los resultados de correr el codigo en un servidor con 1TB de ram con el polinomio escogido (x^31+x^3+1), por la limitación de los computadores personales del equipo.

![Alt text](<pantallazo tarea 2 actividad 2.png>) 

Figura 1. Screenshot de los resultados de la operacion.

![Alt text](<tabla primitivos.png>)

Figura 2. Primitive polynomials for maximum-length LFSRs, extraído del libro Paar C. and Pelzl J.(2010). Understanding Cryptography. Springer.
